version: '3'
services:
  app:
    build:
      context: ./app
    depends_on:
      - fluentd  
    logging:
        driver: "fluentd"
        options:
          fluentd-address: localhost:24224
  fluentd:
    build:
      context: ./fluentd
    image: baritolog-fluentd:latest
    environment:
      - FLUENTD_CONF=fluent.conf
      # Set verbose output
      - FLUENTD_OPT=-v
